# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0808b6e434695c3806c393cf966d8ea11149389c1ab4ddd8cbf23be6d2b730b00f2d394f649624df6d8875f6fdd5acc7d60d9ebe7f7c4c0a84b3dbebaf6ba837

test:
  secret_key_base: f13bc500a1d5ec4c799e056f75db7d22001a29ba67fc9f88219f86287099b024302a4722ff0117685dbefd7c636c814510061b369546dbfb42b56b742d8f08d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
